### ISSUE TITLE
Population of NYC seems off

### ISSUE THREAD

**Issue by duckysherwood** [outbreak-info/outbreak.info#176]
Hi -- looking at your graphs, the number of cases for NYC was 8021 on 15 April 2020, which converted into 41.7 cases per 100k.

8021 cases / (41.7 (cases/100k)) = 192 * 100k => population of 19.2M.

Google says that the population of NYC is 8.399M, which is consistent with my 2011 total for the five boroughs, which I think I got from the Census Bureau.

Using Johns Hopkins, data, I see 7837 cases in the five boroughs on 15 April 2020.

Maybe you are using the metro area, but I don't know which counties you would include to get an additional 10.8M people and only 184 more cases.

Therefore, I think you probably have a problem with your New York case counts or population.

**Comment by gkarthik** [comment]
Thank you for raising this bug. We are using the population of the New York-Newark-Jersey City, NY-NJ-PA metro area. However, you are right and we should be using the population of the following counties: New York, Kings, Queens, Bronx and Richmond Counties. This should be fixed by https://github.com/outbreak-info/biothings_covid19/commit/356fbfbe994cb201ce32af16377c49dc0cc1fe4f
