### ISSUE TITLE
Situation Reports: Add in definition for Variant of Concern vs. Interest

### ISSUE THREAD

**Issue by flaneuse** [outbreak-info/outbreak.info#254]

**Comment by AlaaALatif** [comment]
@EmilyHaag has a great paragraph on this in her upcoming blog post. We could possibly use excerpts from that to add here

**Comment by EmilyHaag** [comment]
https://outbreak.info/blog/what-are-covid-19-mutations

**Definitions paragraphs:**
_The terminology surrounding SARS-CoV-2 mutations is being used very loosely, but distinction is important. A strain of a virus has distinct properties and causes a specific immune response. When a virus has developed a set of mutations that causes it to act differently than that of the original strain, it is classified as a variant. Similarly, lineages are often minor accumulations of mutations, forming a different genetic line of the strain._

_If researchers identify a SARS-CoV-2 variant that have concerning pathogenic properties, the variant is classified as a Variant Under Investigation (VUI) with a year, month, and number. Experts investigate the level of risk the variant poses and may elevate it to the classification Variant of Concern (VOC). The B.1.1.7 variant, for example, was originally classified as VUI-202012/01, but has since been renamed to VOC-202012/01. Researchers also use the term Variant of Interest (VOI) to note a variant that requires further study to identify whether it has clinical significance._

_The key differences between these classifications:_
•	_VOIs and VUIs are variants of increasing prevalence with mutations in biologically important regions but are lacking evidence for increased transmissibility, virulence, and/or immune evasion._
•	_VOCs are variants which have evidence in the literature of increased transmissibility, worse outcomes, and/or decreased vaccine efficacy._

**Comment by flaneuse** [comment]
Might be good to have a situation-reports/definitions page, defining variant, lineage, VOC, VOI.

**Comment by EmilyHaag** [comment]
That's a good idea. I'm happy to draft the copy

**Comment by flaneuse** [comment]
thanks @EmilyHaag! My first pass is on slide 11: https://docs.google.com/presentation/d/1IDoFKl1sTMw3texNs5lpgIkL9U-kfWow48J7roZ9mnY/edit#slide=id.gbdf6337b29_0_24

**Comment by flaneuse** [comment]
closed with #282
