### ISSUE TITLE
Indian Variant B.1.617 has split into 4, only 1 is listed in lineage tracker

### ISSUE THREAD

**Issue by corneliusroemer** [outbreak-info/outbreak.info#349]
About a week ago, the indian variant B.1.617 was split into 4 variants:
B.1.617
B.1.617.1
B.1.617.2
B.1.617.3

Only the first is shown on this site: https://outbreak.info/situation-reports

I don't think there's an easy solution as to which to track. But the current situation doesn't seem right, probably the variant with the largest number of sequences should be tracked, or one that combines all 4, until there's a clear "winner".

**Comment by flaneuse** [comment]
Yep, we've been waiting to make this change at the end of the week along with some other changes to the front-end.  We'll be adding B.1.617.1 as a Variant of Interest (VOI) due to the high presence of the E484Q mutation and the expansion in prevalence of that sublineage within India.

We're also monitoring the other B.1.617 sublineages to see if they start increasing in prevalence, but for the moment to try to be parsimonious with the number of lineages we're tracking, we aren't going to include them as VOIs.

Of course, any lineage can be tracked with a custom report:
https://outbreak.info/situation-reports?pango=B.1.617.1&selected=IND&loc=IND
https://outbreak.info/situation-reports?pango=B.1.617.2&selected=IND&loc=IND
https://outbreak.info/situation-reports?pango=B.1.617.3&selected=IND&loc=IND

or you can look at the lineages in India on the whole with the [India Location Report](https://outbreak.info/location-reports?loc=IND&pango=B.1.617.1&pango=B.1.617.2&pango=B.1.617.3&selected=B.1.1.7&selected=B.1.617.1&selected=B.1.617&selected=B.1.617.2&selected=B.1.617.3)

**Comment by corneliusroemer** [comment]
Thanks for explaining. Yes, I've been looking at the individual reports. I've been studying your api quite closely, it's really good. The best I know to get GISAID sequences analysed. Really good work!
