### ISSUE TITLE
AY.12 looks incorrect

### ISSUE THREAD

**Issue by alurqu** [outbreak-info/outbreak.info#421]
Pango-designation ticket 170 which led to designation of AY.12 explicitly mentions occurrence in Israel, but https://outbreak.info/situation-reports?pango=AY.12&selected=ISR&loc=ISR shows zero of 1245 AY.12 sequences in Israel.  Also, the pango-designation ticket explicitly references mutation S:T791I with an explicit comment associating AY.12 with RNA mutation C23934T which should yield S:T791I, but the mutation table at https://outbreak.info/situation-reports?pango=AY.12 doesn't show S:T791I, and https://outbreak.info/compare-lineages?pango=AY.12 also doesn't show S:T791I.  With these mismatches, there seems to be a possible error either in outbreak.info or upstream in the lineage classifier.

Edit: for reference, the pango-designation ticket for AY.12 is https://github.com/cov-lineages/pango-designation/issues/170.

**Comment by flaneuse** [comment]
Thanks @alurqu for mentioning this. @mindoftea can you please look into it?

**Comment by AlaaALatif** [comment]
Thanks @alurqu for detailing the issue and providing necessary supporting information. We took a look at sequences from the list of accession IDs referenced in the pango-designation ticket, and the mutation was correctly identified in all of them as part of our upstream mutation-calling pipeline (bjorn). The discrepancy you reported is most likely because the recent pango-update hasn't yet been added for re-classifying the lineages of those sequences, which we currently get directly from GISAID's feed. 

![ay12_s_t791i](https://user-images.githubusercontent.com/18534836/129488948-9dff5aa1-537e-425a-a643-d48240d43896.png)


This issue should be fixed as soon as the incoming data has updated lineage classifications, which will likely happen in the next few days. We are also [working on](https://github.com/andersen-lab/bjorn/issues/14) adding updated pango-designations directly to our upstream pipeline, so that these delays can be more avoidable.

**Comment by alurqu** [comment]
An upstream pango-designation ticket related to this issue has recently been opened: https://github.com/cov-lineages/pango-designation/issues/186

**Comment by flaneuse** [comment]
@mindoftea is this fixed?
